/* Venue dataset for the conference facilities guide.
   New Zealand venues with three Tourism Fiji venues spread through.
   NZICC carries real sourced detail; others use realistic placeholder specs. */
(function () {
  const venues = [
    { id: "nzicc", name: "New Zealand International Convention Centre", type: "Convention centre", country: "NZ",
      region: "Auckland", location: "Auckland CBD, New Zealand", capacity: 4500, rooms: 33,
      standfirst: "The country's largest conference and exhibition venue — 33 flexible spaces and a 2,852-seat theatre in the heart of the city.",
      badge: null, featured: true, href: "Conference Facility Guide — NZICC.html", slot: "v-nzicc",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "te-pae", name: "Te Pae Christchurch Convention Centre", type: "Convention centre", country: "NZ",
      region: "Christchurch", location: "Christchurch CBD, New Zealand", capacity: 2000, rooms: 24,
      standfirst: "A riverside centre at the heart of the rebuilt city, with a 1,400-seat auditorium and a 200-booth exhibition hall.",
      badge: null, href: "#", slot: "v-tepae",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "takina", name: "Tākina, Wellington Convention & Exhibition Centre", type: "Convention centre", country: "NZ",
      region: "Wellington", location: "Wellington waterfront, New Zealand", capacity: 1600, rooms: 18,
      standfirst: "The capital's purpose-built centre, steps from Te Papa, pairing exhibition halls with harbour-view function space.",
      badge: null, href: "#", slot: "v-takina",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "sofitel", name: "Sofitel Fiji Resort & Spa", type: "Resort", country: "Fiji",
      region: "Denarau, Fiji", location: "Denarau Island, Nadi, Fiji", capacity: 1000, rooms: 9,
      standfirst: "Beachfront French-Pacific luxury on Denarau, with a pillarless ballroom and incentive programmes by the lagoon.",
      badge: "fiji", href: "#", slot: "v-sofitel",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "claudelands", name: "Claudelands", type: "Convention centre", country: "NZ",
      region: "Waikato", location: "Hamilton, Waikato, New Zealand", capacity: 4000, rooms: 24,
      standfirst: "A vast arena-and-conference complex in the central North Island, built for exhibitions, gala dinners and concerts.",
      badge: null, href: "#", slot: "v-claude",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "aotea", name: "Aotea Centre", type: "Convention centre", country: "NZ",
      region: "Auckland", location: "Aotea Square, Auckland CBD, New Zealand", capacity: 2200, rooms: 8,
      standfirst: "Auckland's civic arts and conference centre on Aotea Square, with a grand auditorium and tiered function rooms.",
      badge: null, href: "#", slot: "v-aotea",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "energy-events", name: "Energy Events Centre", type: "Convention centre", country: "NZ",
      region: "Rotorua", location: "Rotorua lakefront, New Zealand", capacity: 2000, rooms: 12,
      standfirst: "Set on the Rotorua lakefront amid geothermal landscapes — a flexible plenary venue with a strong cultural welcome.",
      badge: null, href: "#", slot: "v-energy",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "baypark", name: "Mercury Baypark", type: "Convention centre", country: "NZ",
      region: "Bay of Plenty", location: "Mount Maunganui, Tauranga, New Zealand", capacity: 4000, rooms: 14,
      standfirst: "A coastal arena-and-conference complex in the Bay of Plenty built for exhibitions, expos and large plenaries.",
      badge: null, href: "#", slot: "v-baypark",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "mfc", name: "Michael Fowler Centre", type: "Convention centre", country: "NZ",
      region: "Wellington", location: "Wellington waterfront, New Zealand", capacity: 2200, rooms: 9,
      standfirst: "The capital's landmark auditorium and function venue, moments from the harbour and the parliamentary precinct.",
      badge: null, href: "#", slot: "v-mfc",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "millbrook", name: "Millbrook Resort", type: "Resort", country: "NZ",
      region: "Queenstown", location: "Arrowtown, Queenstown, New Zealand", capacity: 400, rooms: 5,
      standfirst: "An alpine golf resort near Queenstown pairing executive retreats and incentives with championship fairways and spa.",
      badge: null, href: "#", slot: "v-millbrook",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "cordis", name: "Cordis, Auckland", type: "Hotel", country: "NZ",
      region: "Auckland", location: "Symonds Street, Auckland CBD, New Zealand", capacity: 1200, rooms: 11,
      standfirst: "A five-star city hotel with a grand pillarless ballroom and flexible meeting suites, minutes from the waterfront.",
      badge: null, href: "#", slot: "v-cordis",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "sheraton", name: "Sheraton Fiji Golf & Beach Resort", type: "Resort", country: "Fiji",
      region: "Denarau, Fiji", location: "Denarau Island, Nadi, Fiji", capacity: 1200, rooms: 11,
      standfirst: "A flagship Denarau resort with the largest convention facilities in Fiji — built for association congresses and gala events.",
      badge: "fiji", href: "#", slot: "v-sheraton",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "chch-townhall", name: "Christchurch Town Hall", type: "Convention centre", country: "NZ",
      region: "Christchurch", location: "Kilmore Street, Christchurch, New Zealand", capacity: 2500, rooms: 10,
      standfirst: "A restored modernist icon with world-class acoustics, anchoring conferences and concerts in the central city.",
      badge: null, href: "#", slot: "v-chchth",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "shed10", name: "Shed 10, Queens Wharf", type: "Convention centre", country: "NZ",
      region: "Auckland", location: "Queens Wharf, Auckland waterfront, New Zealand", capacity: 1500, rooms: 4,
      standfirst: "A heritage wharf shed on Auckland's waterfront — raw character and harbour views for gala dinners and launches.",
      badge: null, href: "#", slot: "v-shed10",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "dunedin", name: "Dunedin Centre — Te Whare o Rukutia", type: "Convention centre", country: "NZ",
      region: "Otago", location: "Dunedin, Otago, New Zealand", capacity: 2000, rooms: 15,
      standfirst: "A heritage-meets-modern venue in the south, anchored by the historic Town Hall and a 2,000-seat auditorium.",
      badge: null, href: "#", slot: "v-dunedin",
      facets: { accommodation: false, catering: true, accessibility: true, av: false, sustainability: false } },

    { id: "trafalgar", name: "Trafalgar Centre", type: "Convention centre", country: "NZ",
      region: "Nelson", location: "Nelson, New Zealand", capacity: 2000, rooms: 6,
      standfirst: "Nelson's flexible events arena at the top of the South Island, suited to exhibitions and regional conferences.",
      badge: null, href: "#", slot: "v-trafalgar",
      facets: { accommodation: false, catering: true, accessibility: true, av: false, sustainability: false } },

    { id: "hilton-qt", name: "Hilton Queenstown Resort & Spa", type: "Resort", country: "NZ",
      region: "Queenstown", location: "Kawarau Village, Queenstown, New Zealand", capacity: 350, rooms: 6,
      standfirst: "A lakeside resort on the shores of Lake Wakatipu offering self-contained conference and incentive experiences.",
      badge: null, href: "#", slot: "v-hiltonqt",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "napier", name: "Napier War Memorial Centre", type: "Convention centre", country: "NZ",
      region: "Hawke's Bay", location: "Marine Parade, Napier, New Zealand", capacity: 1200, rooms: 6,
      standfirst: "A refurbished seafront venue on Napier's Marine Parade, pairing Art Deco surrounds with modern function space.",
      badge: null, href: "#", slot: "v-napier",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "tsb-showplace", name: "TSB Showplace", type: "Convention centre", country: "NZ",
      region: "Taranaki", location: "New Plymouth, Taranaki, New Zealand", capacity: 1400, rooms: 7,
      standfirst: "New Plymouth's premier theatre and conference venue, a short walk from the coastal walkway and galleries.",
      badge: null, href: "#", slot: "v-tsb",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "ic-fiji", name: "InterContinental Fiji Golf Resort & Spa", type: "Resort", country: "Fiji",
      region: "Natadola, Fiji", location: "Natadola Bay, Coral Coast, Fiji", capacity: 800, rooms: 8,
      standfirst: "Overlooking one of the South Pacific's finest beaches at Natadola Bay — refined meeting space with championship golf.",
      badge: "fiji", href: "#", slot: "v-icfiji",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "ilt", name: "ILT Stadium Southland", type: "Convention centre", country: "NZ",
      region: "Southland", location: "Invercargill, Southland, New Zealand", capacity: 3000, rooms: 8,
      standfirst: "The deep south's largest indoor venue, combining arena scale with breakout rooms for conferences and expos.",
      badge: null, href: "#", slot: "v-ilt",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "forsyth", name: "Forsyth Barr Stadium", type: "Convention centre", country: "NZ",
      region: "Otago", location: "Dunedin, Otago, New Zealand", capacity: 3000, rooms: 10,
      standfirst: "The world's first fully roofed natural-turf stadium, with tiered lounges and function suites for major events.",
      badge: null, href: "#", slot: "v-forsyth",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: true } },

    { id: "crowne-qt", name: "Crowne Plaza Queenstown", type: "Hotel", country: "NZ",
      region: "Queenstown", location: "Beach Street, Queenstown, New Zealand", capacity: 500, rooms: 7,
      standfirst: "A lakefront hotel in the heart of Queenstown with flexible meeting suites and alpine views over Lake Wakatipu.",
      badge: null, href: "#", slot: "v-crowne",
      facets: { accommodation: true, catering: true, accessibility: true, av: true, sustainability: false } },

    { id: "novotel-ham", name: "Novotel Tainui Hamilton", type: "Hotel", country: "NZ",
      region: "Waikato", location: "Alma Street, Hamilton, New Zealand", capacity: 600, rooms: 6,
      standfirst: "A riverside city hotel in Hamilton offering practical conference rooms and accommodation in the central Waikato.",
      badge: null, href: "#", slot: "v-novotelham",
      facets: { accommodation: true, catering: true, accessibility: true, av: false, sustainability: false } },

    { id: "shed6", name: "Shed 6 & TSB Arena", type: "Convention centre", country: "NZ",
      region: "Wellington", location: "Wellington waterfront, New Zealand", capacity: 2300, rooms: 10,
      standfirst: "Twin waterfront venues offering raw industrial character and arena scale for conferences and large exhibitions.",
      badge: null, href: "#", slot: "v-shed6",
      facets: { accommodation: false, catering: true, accessibility: true, av: true, sustainability: false } },
  ];

  const fmt = (n) => n.toLocaleString("en-NZ");

  const articles = [
    { id: "a1", category: "companies", kicker: "Business events",
      title: "Inside NZICC: how a $750m venue is reshaping Auckland's events economy",
      standfirst: "The country's largest convention centre has opened its doors — and the business-travel map of New Zealand is being redrawn.",
      author: "Pattrick Smellie", readTime: "6 min read", date: "2 days ago", slot: "art-1",
      href: "Conference Facility Guide — NZICC.html" },
    { id: "a2", category: "the-life", kicker: "Travel",
      title: "The rise of ‘bleisure’: why delegates are staying on — and spending more",
      standfirst: "Tacking a holiday onto a work trip is booming, and venues are rebuilding their offers around it.",
      author: "Jenny Ruth", readTime: "4 min read", date: "3 days ago", slot: "art-2", href: "#" },
    { id: "a3", category: "world", kicker: "Pacific",
      title: "Fiji's pitch to the incentive market: sun, service and a short-haul flight",
      standfirst: "Tourism Fiji is courting Australasian conference organisers with a distinctly Pacific proposition.",
      author: "Rebecca Howard", readTime: "5 min read", date: "4 days ago", slot: "art-3", href: "#" },
    { id: "a4", category: "technology", kicker: "Technology",
      title: "Hybrid is here to stay: what it means for venue technology",
      standfirst: "AV, streaming and the new economics of the half-in-person conference.",
      author: "Peter Griffin", readTime: "4 min read", date: "5 days ago", slot: "art-4", href: "#" },
    { id: "a5", category: "property", kicker: "Property",
      title: "Queenstown after the conference: where delegates linger",
      standfirst: "The resort town has become a magnet for executive retreats and post-event escapes.",
      author: "Maria Slade", readTime: "3 min read", date: "1 week ago", slot: "art-5", href: "#" },
    { id: "a6", category: "markets", kicker: "Markets",
      title: "Hotel investors pile into New Zealand as event tourism rebounds",
      standfirst: "Operators are betting on a sustained lift in delegate nights through 2027.",
      author: "Rebecca Stevenson", readTime: "4 min read", date: "5:00am", slot: "art-6", href: "#" },
    { id: "a7", category: "finance", kicker: "Aviation",
      title: "Airlines add trans-Tasman capacity as event travel climbs",
      standfirst: "Carriers are scheduling extra services around the conference calendar.",
      author: "Andy Macdonald", readTime: "3 min read", date: "5:00am", slot: "art-7", href: "#" },
    { id: "a8", category: "opinion", kicker: "Opinion",
      title: "The conference dollar matters more than ever for the regions",
      standfirst: "Business events punch well above their weight for local economies.",
      author: "Pattrick Smellie", readTime: "4 min read", date: "5:00am", slot: "art-8", href: "#" },
  ];

  window.GUIDE = {
    venues: venues,
    regions: ["Auckland", "Wellington", "Christchurch", "Waikato", "Bay of Plenty", "Taranaki",
      "Nelson", "Hawke's Bay", "Rotorua", "Otago", "Southland", "Queenstown",
      "Denarau, Fiji", "Natadola, Fiji"],
    types: ["Convention centre", "Resort", "Hotel"],
    facetLabels: {
      accommodation: "Accommodation on-site",
      catering: "In-house catering",
      av: "AV & production",
      accessibility: "Accessibility",
      sustainability: "Sustainability credentials",
    },
    fmt: fmt,
    articles: articles,
  };
})();
